Update README.md - T3AS
c0d3z3r0/aixun_t3a_rev pull request #2
Opened 2023-04-21 13:38 UTC by ireun

2023-04-21 19:21 UTC, c0d3z3r0 requested changes

2023-04-21 19:21 UTC, c0d3z3r0 commented on README.md
> +T3AS firmware is for GD32F305/GD32F307 version of the board, which [was](https://www.aixuntech.com/newsinfo/aixun-new-product-launch-t3as-allinone-200w-soldering-station/) released in February of 202
`which was [released](https://www.aixuntech.com/newsinfo/aixun-new-product-launch-t3as-allinone-200w-soldering-station/)`

2023-04-21 19:23 UTC, c0d3z3r0 approved these changes

2023-04-21 19:24 UTC, merged

2023-04-21 19:25 UTC, c0d3z3r0 commented on README.md
> +T3AS firmware is for GD32F305/GD32F307 version of the board, which [was](https://www.aixuntech.com/newsinfo/aixun-new-product-launch-t3as-allinone-200w-soldering-station/) released in February of 202
oops, "in February of 2023" got missing

2023-04-21 19:26 UTC, c0d3z3r0 commented on README.md
> +T3AS firmware is for GD32F305/GD32F307 version of the board, which [was](https://www.aixuntech.com/newsinfo/aixun-new-product-launch-t3as-allinone-200w-soldering-station/) released in February of 202
fixed

2023-04-22 23:53 UTC, ireun commented
@c0d3z3r0 do you use Discord? Or is there any other way of contacting You?

2023-04-23 09:57 UTC, c0d3z3r0 commented
No Discord, but feel free to drop me a pm on eevblog forums or libera.chat IRC